# Name / Bio
name: Jack Zhang
bio: 'A Man who travels the world eating noodles.'

# Avatar, if it is an external image, update external-avatar for true
avatar: https://avatars.githubusercontent.com/u/6365092
external-avatar: true

# Base URL
# url: http://127.0.0.1:4000
url: http://mushank.github.io

# Permalink
permalink: ./post/:title/


# Site modules, if you do not need someone, comment it.
blog: true
projects: true
about: true

# Page width | options: [normal, large] | normal = 560px / large = 810px | default: normal 
width: normal

# Page number, if you do not want to show pagination, comment below
# paginate: 7
# paginate_path: ./pagination/:num/

# Read time, if you do not want to show the read time of the posts, update read-time for false
read-time: true

# Tags, if you do not want to show the tags inside the posts, update show-tags for false
show-tags: true

# Related posts, if you do not want to show related posts inside a post, update related for false
related: true

# Animation, if you do not want any animations, update animation for false
animation: true

# Markdown
markdown: kramdown

# Highlighter
highlighter: rouge

# Social links, comment the ones you do not want to show
github: mushank
email: mushank@Gmail.com
# facebook: myfacebook
# twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
# medium: medium

# Widgets
# disqus: 'Your-Disqus-Short-Name'
# analytics-google: 'Your-Google-Analytics-Account'


####################################################
# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  # - jemoji
  # - jekyll-mentions
  # - jekyll-feed

jekyll-mentions:
    base_url: https://github.com

# Files you do not want Jekyll to deal with
exclude: [_site]
