# Name / bio
name: Jack Zhang
bio: 'A Man who travels the world eating noodles.'
# Avatar, if it is an external image, update external-avatar for true
avatar: https://avatars.githubusercontent.com/u/6365092
external-avatar: true

# Base URL
url: http://127.0.0.1:4000
# url: http://mushank.github.io

# Settings
permalink: ./:title/
markdown: kramdown
highlighter: rouge

# Page width | options: [normal, large] | normal = 560px / large = 810px | default: normal 
width: large

# Page number, if you do not want to show pagination, comment below
# paginate: 10
# paginate_path: "blog/:num/"

# if you don't need these items, comment them below
blog: true
projects: true
about: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

# socials
# facebook: myfacebook
# twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: mushank
# medium: medium
email: mushank@Gmail.com

# Widgets
# disqus: false
# analytics-google: 'Your-Google-Analytics-Account'

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
